name: E-Permit CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: epermit-api
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # BUILD IMAGE
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # INSTALL TRIVY
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.55.0/trivy_0.55.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.55.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      # SECURITY GATE
      - name: Security Scan (CRITICAL FAIL)
        run: |
          trivy image \
            --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            $IMAGE_NAME:$IMAGE_TAG

      # REPORT
      - name: Generate SARIF Report
        if: always()
        run: |
          trivy image \
            --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            --format sarif \
            --output trivy-results.sarif \
            $IMAGE_NAME:$IMAGE_TAG

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.sarif

      # SIMULATE ECR
      - name: Simulate ECR Login
        run: echo "ECR login simulated"

      - name: Simulate Push
        run: echo "Image pushed to ECR (simulation)"
